#!/usr/bin/env bash
# This script manages the nvidia dGPU power state for different performance modes in Muxless laptops, like the ASUS ROG G14 2020 model.
# It can switch between three modes:
#  - off: Turns off the GPU to save power.
#  - on: Turns on the GPU for maximum performance.
#
# In order to function correctly, this script requires to be executed as root user.

# GPU PCI address
GPU_PCI="0000:01:00.0"
AUDIO_PCI="0000:01:00.1"
USB_HOST_PCI="0000:01:00.2"
USB_C_PCI="0000:01:00.3"

# Main functions
kill_gpu_processes() {
    # Close any processes that may block GPU unload
    pkill -f nvidia || true
}

unload_nvidia() {
    modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia i2c_nvidia_gpu 2>/dev/null || true
}

# Not necessary because modules are reloaded automatically on device reattachment
# load_nvidia() {
#     modprobe nvidia_uvm || true
#     modprobe nvidia_modeset || true
#     modprobe nvidia_drm || true
#     modprobe nvidia || true
# }

reattach_nvidia_devices() {
    echo 1 > /sys/bus/pci/rescan
}

detach_nvidia_devices() {
    echo 1 > /sys/bus/pci/devices/$GPU_PCI/remove
    echo 1 > /sys/bus/pci/devices/$AUDIO_PCI/remove
    echo 1 > /sys/bus/pci/devices/$USB_HOST_PCI/remove
    echo 1 > /sys/bus/pci/devices/$USB_C_PCI/remove
}

# Modes:
MODE="$1"

case "$MODE" in
    off)
        echo "[OFF] Shutting down GPU..."
        kill_gpu_processes
        unload_nvidia
        detach_nvidia_devices
        echo "GPU OFF (removed from PCI bus)"
        ;;

    on)
        echo "[ON] Activating GPU..."
        # load_nvidia
        reattach_nvidia_devices
        # power_on
        echo "GPU ON (attached to PCI bus)"
        ;;

    # auto)
    #     echo "[AUTO] Hybrid mode: GPU idle when inactive"
    #     # load_nvidia
    #     reattach_nvidia_devices
    #     # power_auto
    #     echo "GPU idle / low-power attivo"
    #     ;;

    *)
        echo "Usage: gpu-mode {on|off}"
        exit 1
        ;;
esac
